### ISSUE TITLE
_PIPE_BUF not defined error

### ISSUE THREAD

**Issue by nhooyr** [seveas/whelk#7]
Getting this error [here](https://github.com/seveas/whelk/blob/03406c86a4435b698b9144ce674c8c8a994d8b5e/whelk/subprocess_32.py#L109).

I also think I'd get the same error [here](https://github.com/seveas/whelk/blob/03406c86a4435b698b9144ce674c8c8a994d8b5e/whelk/subprocess_33.py#L149)

I changed it to `subprocess._PIPE_BUF` and it works.

**Comment by seveas** [comment]
The text _PIPE_BUFF does not appear in the whelk sources. The files you link to spell it correctly. I don't see the bug you're describing.

**Comment by nhooyr** [comment]
I meant `_PIPE_BUF`

**Comment by nhooyr** [comment]
```
Traceback (most recent call last):
  File "/usr/local/bin/git-hub", line 11, in <module>
    GitHub().main()
  File "/usr/local/lib/python2.7/site-packages/gitspindle/__init__.py", line 335, in main
    self.login()
  File "/usr/local/lib/python2.7/site-packages/gitspindle/github.py", line 39, in login
    token = self.config('token')
  File "/usr/local/lib/python2.7/site-packages/gitspindle/__init__.py", line 114, in config
    return self.config_secret(key, value)
  File "/usr/local/lib/python2.7/site-packages/gitspindle/__init__.py", line 139, in config_secret
    credential.fill_noninteractive()
  File "/usr/local/lib/python2.7/site-packages/gitspindle/__init__.py", line 483, in fill_noninteractive
    self.communicate('fill', env=env)
  File "/usr/local/lib/python2.7/site-packages/gitspindle/__init__.py", line 499, in communicate
    ret = self.shell.git('-c', 'core.askpass=', 'credential', action, env=env, input=data)
  File "/usr/local/lib/python2.7/site-packages/whelk/__init__.py", line 181, in __call__
    (out, err) = sp.communicate(self.input)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 800, in communicate
    return self._communicate(input)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1419, in _communicate
    stdout, stderr = self._communicate_with_select(input)
  File "/usr/local/lib/python2.7/site-packages/whelk/subprocess_32.py", line 109, in _communicate_with_select
    chunk = input[input_offset : input_offset + _PIPE_BUF]
NameError: global name '_PIPE_BUF' is not defined
```

**Comment by seveas** [comment]
Ah, yes, now I see. Easy fix, but it looks like your python setup is buggy too: it's compiled without polling support. A python install that properly supports polling wouldn't hit this fallback path, which has been buggy since the first release of whelk. Looks like nobody has hit this so far (or at least not reported it), because python very rarely gets compiled without polling support.

**Comment by nhooyr** [comment]
Polling isn't fully implemented in OSX.

**Comment by seveas** [comment]
I've been using whelk on osx myself since oct 2017 and it works just fine, so closing this stale issue,
